apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "0 0 1 1 * *" #monthly 1AM of 1st (or about then)
  - name: route
    value: "api/mammon/cron"