apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mammon-cron
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "0 0 1 {{ .Values.cron.BillingPeriodStartDayInMonth }} * *" #monthly 1AM of day after billing period ends (or about then)
  - name: route
    value: "api/mammon/cron"