name: CD for Mammon

on:
    workflow_dispatch:
    push:
        branches:
        - main
        - .github/workflows/cd.yaml
        - src/**/*.cs
        - src/**/*.json

permissions:
    id-token: write
    contents: read
    pull-requests: read

jobs:
    Mammon_CD:
        uses: ./.github/workflows/shared-app-cd-workflow.yaml
        secrets:
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_PLATFORM_SUBSCRIPTION_ID: ${{ secrets.AZURE_PLATFORM_SUBSCRIPTION_ID }}
            AZURE_DEV_SUBSCRIPTION_ID: ${{ secrets.AZURE_DEV_SUBSCRIPTION_ID }}
            AZURE_PROD_SUBSCRIPTION_ID: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
            ACTIONS_AUTH_APP_ID: ${{ secrets.ACTIONS_AUTH_APP_ID }}
            ACTIONS_AUTH_APP_PRIVATE_KEY: ${{ secrets.ACTIONS_AUTH_APP_PRIVATE_KEY }}
        with:
            applicationFolder: Mammon
            applicationName: mammon