name: CI for Mammon

on:
  workflow_dispatch:

  pull_request:
    paths:
      - .github/workflows/ci.yaml
      - src/**/*.cs
      - src/**/*.json

permissions:
      id-token: write
      contents: read

jobs:
  Mammon_CI:
    uses: ./.github/workflows/shared-app-ci-workflow.yaml
    with:
      applicationName: Mammon