name: CI for Mammon

on:
  workflow_dispatch:

  pull_request:
    paths:
      - .github/workflows/ci.yaml
      - src/**/*.cs
      - src/**/*.json

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:
  Mammon_CI:
    uses: ./.github/workflows/shared-app-ci-workflow.yaml
    secrets:
      ACTIONS_AUTH_APP_ID: ${{ secrets.ACTIONS_AUTH_APP_ID }}
      ACTIONS_AUTH_APP_PRIVATE_KEY: ${{ secrets.ACTIONS_AUTH_APP_PRIVATE_KEY }}
    with:
      applicationFolder: Mammon