name: Shared Application CI Workflow

on:
  workflow_call:
    secrets:
      ACTIONS_AUTH_APP_ID:
        required: true
        description: 'GitHub App ID'
      ACTIONS_AUTH_APP_PRIVATE_KEY:
        required: true
        description: 'GitHub App Private Key'
    inputs:
      applicationFolder:
        type: string
        required: true
        description: Application Folder
      
jobs:
  app_ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: gh-app-install token
        id: gh-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.ACTIONS_AUTH_APP_ID }}
          private_key: ${{ secrets.ACTIONS_AUTH_APP_PRIVATE_KEY }}        

      - name: checkout cost centre definition repo
        uses: actions/checkout@v3
        with:
          path: costcentre-definitions
          repository: Uniphar/costcentre-definitions
          ref: refs/heads/feature/initFile ##TODO: change to main
          token: ${{ steps.gh-app.outputs.token }}

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'

      - name: expose app name into env
        run: |
          echo "APPLICATION_FOLDER=${{ inputs.applicationFolder }}" >> $GITHUB_ENV
          
      - name: run unit tests
        working-directory: ./src/${{ env.APPLICATION_FOLDER }}.Tests
        run: |
          dotnet test --filter TestCategory=UnitTest

      - name: add cost centre rule file
        run: cp ./costcentre-definitions/costCentreRules.json src
        
      - name: docker build test
        working-directory: ./src/
        run: |
          docker build . -f ./$APPLICATION_FOLDER/Dockerfile
      
      - name: check for NuGet vulnerabilites
        working-directory: ./src/
        shell: pwsh
        run: |
            dotnet restore
            dotnet list package --vulnerable --include-transitive 2>&1 | tee build.log
            echo "Analyze dotnet list package command log output..."
            exit (Select-String -Path "build.log" -Pattern "has the following vulnerable packages" -AllMatches).Matches.Count -gt 0 ? 1 : 0

      - name: Initialize-SubscriptionsRBAC WhatIf
        uses: azure/powershell@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} #required for gh cli to determine "current PR"
        with: 
          inlineScript: |
           . ./devops/Initialize-SubscriptionsRBAC.ps1
            Initialize-SubscriptionsRBAC ./costcentre-definitions/costCentreRules.json test -WhatIf
          azPSVersion: "latest"
          errorActionPreference: 'stop'
          failOnStandardError: true  